CREATE SEQUENCE U_NO;
CREATE SEQUENCE G_NO;
CREATE SEQUENCE M_NO;
CREATE SEQUENCE MC_NO;
CREATE SEQUENCE N_NO;
CREATE SEQUENCE NC_NO;
CREATE SEQUENCE I_NO;
CREATE SEQUENCE IC_NO;
-------------------------------------------------

CREATE TABLE "U_INFO" (
	"U_NO"	NUMBER		NOT NULL,
	"U_GRADE"	VARCHAR2(100)		NOT NULL,
	"U_ID"	VARCHAR2(100)		NOT NULL,
	"U_PW"	VARCHAR2(100)		NOT NULL,
	"U_NAME"	VARCHAR2(100)		NOT NULL,
	"U_AGE"	NUMBER		NOT NULL,
	"U_MAIL"	VARCHAR2(1000)		NOT NULL,
	"U_LO"	VARCHAR2(1000)		NOT NULL,
	"U_GEN"	VARCHAR2(100)		NOT NULL,
	"U_PHONE"	NUMBER		NOT NULL,
	"U_DATE"	DATE		NOT NULL,
	"U_IMG"	VARCHAR2(100)		NULL
);

CREATE TABLE "G_INFO" (
	"G_NO"	NUMBER		NOT NULL,
	"G_TITLE"	VARCHAR2(100)		NULL,
	"G_COM"	VARCHAR2(1000)		NOT NULL,
	"G_DATED"	DATE		NOT NULL,
	"G_IMG"	VARCHAR2(1000)		NULL
);

CREATE TABLE "P_INFO" (
	"U_NO"	NUMBER		NOT NULL,
	"G_NO"	NUMBER		NOT NULL,
	"P_GRADE"	VARCHAR2(100)		NOT NULL,
	"P_DATE"	DATE		NOT NULL
);

CREATE TABLE "M_INFO" (
	"M_NO"	NUMBER		NOT NULL,
	"U_NO"	NUMBER		NOT NULL,
	"G_NO"	NUMBER		NOT NULL,
	"M_TITLE"	VARCHAR2(100)		NOT NULL,
	"M_NP"	NUMBER		NOT NULL,
	"M_COM"	VARCHAR2(1000)		NOT NULL,
	"M_LO"	VARCHAR2(1000)		NOT NULL,
	"M_CD"	DATE		NOT NULL,
	"M_ED"	DATE		NOT NULL,
	"M_MD"	DATE		NULL
);

CREATE TABLE "N_INFO" (
	"N_NO"	NUMBER		NOT NULL,
	"U_NO"	NUMBER		NOT NULL,
	"G_NO"	NUMBER		NOT NULL,
	"N_TITLE"	VARCHAR2(100)		NOT NULL,
	"N_CONTENT"	VARCHAR2(1000)		NOT NULL,
	"N_DATE"	DATE		NOT NULL
);

CREATE TABLE "R_INFO" (
	"M_NO"	NUMBER		NOT NULL,
	"U_NO"	NUMBER		NOT NULL,
	"G_NO"	NUMBER		NOT NULL,
	"R_CONTENT"	VARCHAR2(1000)		NULL,
	"R_STAR"	NUMBER		NULL
);

CREATE TABLE "N_COMMENT" (
	"NC_NO"	NUMBER		NOT NULL,
	"N_NO"	NUMBER		NOT NULL,
	"U_NO"	NUMBER		NOT NULL,
	"G_NO"	NUMBER		NOT NULL,
	"NC_WRITE"	VARCHAR2(1000)		NOT NULL,
	"NC_DATED"	DATE		NOT NULL
);

CREATE TABLE "I_INFO" (
	"I_NO"	NUMBER		NOT NULL,
	"M_NO"	NUMBER		NOT NULL,
	"U_NO"	NUMBER		NOT NULL,
	"G_NO"	NUMBER		NOT NULL,
	"I_TITLE"	VARCHAR2(100)		NULL,
	"I_CONTENT"	VARCHAR2(1000)		NULL,
	"I_DATE"	DATE		NULL
);

CREATE TABLE "I_COMMENT" (
	"IC_NO"	NUMBER		NOT NULL,
	"I_NO"	NUMBER		NOT NULL,
	"M_NO"	NUMBER		NOT NULL,
	"U_NO"	NUMBER		NOT NULL,
	"G_NO"	NUMBER		NOT NULL,
	"IC_WRITE"	VARCHAR2(1000)		NOT NULL,
	"IC_DATED"	DATE		NOT NULL
);

CREATE TABLE "M_COMMENT" (
	"MC_NO"	NUMBER		NOT NULL,
	"M_NO"	NUMBER		NOT NULL,
	"U_NO"	NUMBER		NOT NULL,
	"G_NO"	NUMBER		NOT NULL,
	"MC_WRITE"	VARCHAR2(1000)		NOT NULL,
	"MC_DATED"	DATE		NOT NULL
);

---------------------------------------------------------------

ALTER TABLE "U_INFO" ADD CONSTRAINT "PK_U_INFO" PRIMARY KEY (
	"U_NO"
);

ALTER TABLE "G_INFO" ADD CONSTRAINT "PK_G_INFO" PRIMARY KEY (
	"G_NO"
);

ALTER TABLE "P_INFO" ADD CONSTRAINT "PK_P_INFO" PRIMARY KEY (
	"U_NO",
	"G_NO"
);

ALTER TABLE "M_INFO" ADD CONSTRAINT "PK_M_INFO" PRIMARY KEY (
	"M_NO",
	"U_NO",
	"G_NO"
);

ALTER TABLE "N_INFO" ADD CONSTRAINT "PK_N_INFO" PRIMARY KEY (
	"N_NO",
	"U_NO",
	"G_NO"
);

ALTER TABLE "R_INFO" ADD CONSTRAINT "PK_R_INFO" PRIMARY KEY (
	"M_NO",
	"U_NO",
	"G_NO"
);

ALTER TABLE "N_COMMENT" ADD CONSTRAINT "PK_N_COMMENT" PRIMARY KEY (
	"NC_NO",
	"N_NO",
	"U_NO",
	"G_NO"
);

ALTER TABLE "I_INFO" ADD CONSTRAINT "PK_I_INFO" PRIMARY KEY (
	"I_NO",
	"M_NO",
	"U_NO",
	"G_NO"
);

ALTER TABLE "I_COMMENT" ADD CONSTRAINT "PK_I_COMMENT" PRIMARY KEY (
	"IC_NO",
	"I_NO",
	"M_NO",
	"U_NO",
	"G_NO"
);

ALTER TABLE "M_COMMENT" ADD CONSTRAINT "PK_M_COMMENT" PRIMARY KEY (
	"MC_NO",
	"M_NO",
	"U_NO",
	"G_NO"
);

--------------------------------------------------------------------

ALTER TABLE "P_INFO" ADD CONSTRAINT "FK_U_INFO_TO_P_INFO_1" FOREIGN KEY (
	"U_NO"
)
REFERENCES "U_INFO" (
	"U_NO"
);

ALTER TABLE "P_INFO" ADD CONSTRAINT "FK_G_INFO_TO_P_INFO_1" FOREIGN KEY (
	"G_NO"
)
REFERENCES "G_INFO" (
	"G_NO"
);

ALTER TABLE "M_INFO" ADD CONSTRAINT "FK_P_INFO_TO_M_INFO_1" FOREIGN KEY (
	"U_NO","G_NO"
)
REFERENCES "P_INFO" (
	"U_NO","G_NO"
);


ALTER TABLE "N_INFO" ADD CONSTRAINT "FK_P_INFO_TO_N_INFO_1" FOREIGN KEY (
	"U_NO","G_NO"
)
REFERENCES "P_INFO" (
	"U_NO","G_NO"
);


ALTER TABLE "R_INFO" ADD CONSTRAINT "FK_M_INFO_TO_R_INFO_1" FOREIGN KEY (
	"M_NO","U_NO","G_NO"
)
REFERENCES "M_INFO" (
	"M_NO","U_NO","G_NO"
);



ALTER TABLE "N_COMMENT" ADD CONSTRAINT "FK_N_INFO_TO_N_COMMENT_1" FOREIGN KEY (
	"N_NO","U_NO","G_NO"
)
REFERENCES "N_INFO" (
	"N_NO","U_NO","G_NO"
);



ALTER TABLE "I_INFO" ADD CONSTRAINT "FK_M_INFO_TO_I_INFO_1" FOREIGN KEY (
	"M_NO","U_NO","G_NO"
)
REFERENCES "M_INFO" (
	"M_NO","U_NO","G_NO"
);


ALTER TABLE "I_COMMENT" ADD CONSTRAINT "FK_I_INFO_TO_I_COMMENT_1" FOREIGN KEY (
	"I_NO","M_NO","U_NO","G_NO"
)
REFERENCES "I_INFO" (
	"I_NO","M_NO","U_NO","G_NO"
);


ALTER TABLE "M_COMMENT" ADD CONSTRAINT "FK_M_INFO_TO_M_COMMENT_1" FOREIGN KEY (
	"M_NO","U_NO","G_NO"
)
REFERENCES "M_INFO" (
	"M_NO","U_NO","G_NO"
);

-----------------------------------------------

INSERT INTO U_INFO
VALUES (U_NO.NEXTVAL, 'MANAGER', 'ADMIN', '1234', 20, '서울', '남자', 01012345678, SYSDATE, NULL);

-----------------------------------------------
DROP TABLE U_INFO;
DROP TABLE G_INFO;
DROP TABLE P_INFO;
DROP TABLE N_INFO;
DROP TABLE N_COMMENT;
DROP TABLE M_INFO;
DROP TABLE M_COMMENT;
DROP TABLE I_INFO;
DROP TABLE I_COMMENT;
DROP TABLE R_INFO;

DROP SEQUENCE U_NO;
DROP SEQUENCE G_NO;
DROP SEQUENCE M_NO;
DROP SEQUENCE MC_NO;
DROP SEQUENCE N_NO;
DROP SEQUENCE NC_NO;
DROP SEQUENCE I_NO;
DROP SEQUENCE IC_NO;
