CREATE SEQUENCE USER_NO;
CREATE SEQUENCE MEETING_NO;
CREATE SEQUENCE GROUP_NO;
CREATE SEQUENCE COMMENT_NO;
CREATE SEQUENCE NOTICE_NO;
CREATE SEQUENCE REVIEW_NO;

CREATE TABLE "USER" (
	"USER_NO"	NUMBER		NOT NULL,
	"USER_GRADE"	VARCHAR(100)		NOT NULL,
	"USER_ID"	VARCHAR(100)		NOT NULL,
	"USER_PW"	VAR		NOT NULL,
	"USER_AGE"	NUMBER		NOT NULL,
	"USER_LO"	VARCHAR(1000)		NOT NULL,
	"USER_GEN"	VARCHAR(100)		NOT NULL,
	"USER_PHONE"	NUMBER		NOT NULL,
	"USER_DATE"	DATE		NOT NULL,
	"USER_IMG"	VARCHAR(100)		NULL
);

CREATE TABLE "GROUP" (
	"G_NO"	NUMBER		NOT NULL,
	"G_COM"	VARCHAR(1000)		NOT NULL,
	"G_DATED"	DATE		NOT NULL,
	"G_IMG"	VARCHAR(1000)		NOT NULL
);

CREATE TABLE "MEMBER" (
	"USER_NO"	NUMBER		NOT NULL,
	"G_NO"	NUMBER		NOT NULL,
	"GRADE"	VARCHAR(100)		NOT NULL,
	"M_DATE"	DATE		NOT NULL
);

CREATE TABLE "MEETING" (
	"M_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"G_NO"	NUMBER		NOT NULL,
	"M_TITLE"	VARCHAR(100)		NOT NULL,
	"M_NP"	VARCHAR(100)		NOT NULL,
	"M_COM"	VARCHAR(1000)		NOT NULL,
	"M_LO"	VARCHAR(1000)		NOT NULL,
	"M_DATED"	DATE		NOT NULL,
	"M_END"	DATE		NOT NULL
);

CREATE TABLE "JOIN" (
	"M_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL
);

CREATE TABLE "notice" (
	"N_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"G_NO"	NUMBER		NOT NULL,
	"N_TITLE"	VARCHAR(100)		NOT NULL,
	"N_CONTENT"	VARCHAR(1000)		NOT NULL,
	"N_DATE"	DATE		NOT NULL
);

CREATE TABLE "REVIEW" (
	"R_NO"	VARCHAR(1000)		NOT NULL,
	"M_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"R_CONTENT"	VARCHAR(1000)		NOT NULL,
	"R_STAR"	NUMBER		NOT NULL
);

CREATE TABLE "COMMENT" (
	"C_NO"	NUMBER		NOT NULL,
	"N_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"C_WRITE"	VARCHAR(1000)		NOT NULL,
	"C_DATED"	DATE		NOT NULL
);

ALTER TABLE "USER" ADD CONSTRAINT "PK_USER" PRIMARY KEY (
	"USER_NO"
);

ALTER TABLE "GROUP" ADD CONSTRAINT "PK_GROUP" PRIMARY KEY (
	"G_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"USER_NO",
	"G_NO"
);

ALTER TABLE "MEETING" ADD CONSTRAINT "PK_MEETING" PRIMARY KEY (
	"M_NO",
	"USER_NO",
	"G_NO"
);

ALTER TABLE "JOIN" ADD CONSTRAINT "PK_JOIN" PRIMARY KEY (
	"M_NO",
	"USER_NO"
);

ALTER TABLE "notice" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY (
	"N_NO",
	"USER_NO",
	"G_NO"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "PK_REVIEW" PRIMARY KEY (
	"R_NO",
	"M_NO",
	"USER_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY (
	"C_NO",
	"N_NO",
	"USER_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "FK_USER_TO_MEMBER_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "USER" (
	"USER_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "FK_GROUP_TO_MEMBER_1" FOREIGN KEY (
	"G_NO"
)
REFERENCES "GROUP" (
	"G_NO"
);

ALTER TABLE "MEETING" ADD CONSTRAINT "FK_MEMBER_TO_MEETING_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "MEMBER" (
	"USER_NO"
);

ALTER TABLE "MEETING" ADD CONSTRAINT "FK_MEMBER_TO_MEETING_2" FOREIGN KEY (
	"G_NO"
)
REFERENCES "MEMBER" (
	"G_NO"
);

ALTER TABLE "JOIN" ADD CONSTRAINT "FK_MEETING_TO_JOIN_1" FOREIGN KEY (
	"M_NO"
)
REFERENCES "MEETING" (
	"M_NO"
);

ALTER TABLE "JOIN" ADD CONSTRAINT "FK_MEMBER_TO_JOIN_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "MEMBER" (
	"USER_NO"
);

ALTER TABLE "notice" ADD CONSTRAINT "FK_MEMBER_TO_notice_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "MEMBER" (
	"USER_NO"
);

ALTER TABLE "notice" ADD CONSTRAINT "FK_MEMBER_TO_notice_2" FOREIGN KEY (
	"G_NO"
)
REFERENCES "MEMBER" (
	"G_NO"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_JOIN_TO_REVIEW_1" FOREIGN KEY (
	"M_NO"
)
REFERENCES "JOIN" (
	"M_NO"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_JOIN_TO_REVIEW_2" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "JOIN" (
	"USER_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_notice_TO_COMMENT_1" FOREIGN KEY (
	"N_NO"
)
REFERENCES "notice" (
	"N_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_MEMBER_TO_COMMENT_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "MEMBER" (
	"USER_NO"
);